<?php
/**
 * ShipmentServiceOptionsNotification
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AntibodiesOnline\UpsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ship
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AntibodiesOnline\UpsApi\Shipping;

use \ArrayAccess;
use \AntibodiesOnline\UpsApi\ObjectSerializer;

/**
 * ShipmentServiceOptionsNotification Class Doc Comment
 *
 * @category Class
 * @description Container for the Quantum View Notification (QVN) is valid for all shipments including Return service, Import Control and Returns Flexible Access.  Valid return service types are: ERL, PRL, PNM, RS1, or RS3.   The shipment level notification is valid for forward and return international shipments as well as for domestic shipments (for US and PR).
 * @package  AntibodiesOnline\UpsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ShipmentServiceOptionsNotification implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ShipmentServiceOptions_Notification';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'notification_code' => 'string',
        'e_mail' => '\AntibodiesOnline\UpsApi\Shipping\NotificationEMail',
        'voice_message' => '\AntibodiesOnline\UpsApi\Shipping\NotificationVoiceMessage',
        'text_message' => '\AntibodiesOnline\UpsApi\Shipping\NotificationTextMessage',
        'locale' => '\AntibodiesOnline\UpsApi\Shipping\NotificationLocale'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'notification_code' => null,
        'e_mail' => null,
        'voice_message' => null,
        'text_message' => null,
        'locale' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'notification_code' => false,
		'e_mail' => false,
		'voice_message' => false,
		'text_message' => false,
		'locale' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'notification_code' => 'NotificationCode',
        'e_mail' => 'EMail',
        'voice_message' => 'VoiceMessage',
        'text_message' => 'TextMessage',
        'locale' => 'Locale'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'notification_code' => 'setNotificationCode',
        'e_mail' => 'setEMail',
        'voice_message' => 'setVoiceMessage',
        'text_message' => 'setTextMessage',
        'locale' => 'setLocale'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'notification_code' => 'getNotificationCode',
        'e_mail' => 'getEMail',
        'voice_message' => 'getVoiceMessage',
        'text_message' => 'getTextMessage',
        'locale' => 'getLocale'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('notification_code', $data ?? [], null);
        $this->setIfExists('e_mail', $data ?? [], null);
        $this->setIfExists('voice_message', $data ?? [], null);
        $this->setIfExists('text_message', $data ?? [], null);
        $this->setIfExists('locale', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['notification_code'] === null) {
            $invalidProperties[] = "'notification_code' can't be null";
        }
        if ((mb_strlen($this->container['notification_code']) > 1)) {
            $invalidProperties[] = "invalid value for 'notification_code', the character length must be smaller than or equal to 1.";
        }

        if ((mb_strlen($this->container['notification_code']) < 1)) {
            $invalidProperties[] = "invalid value for 'notification_code', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['e_mail'] === null) {
            $invalidProperties[] = "'e_mail' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets notification_code
     *
     * @return string
     */
    public function getNotificationCode()
    {
        return $this->container['notification_code'];
    }

    /**
     * Sets notification_code
     *
     * @param string $notification_code The type of notification requested.  Valid values:  5 - QV In-transit Notification 6 - QV Ship Notification 7 - QV Exception Notification 8 - QV Delivery Notification 2 - Return Notification or Label Creation Notification 012 - Alternate Delivery Location Notification 013 - UAP Shipper Notification
     *
     * @return self
     */
    public function setNotificationCode($notification_code)
    {
        if (is_null($notification_code)) {
            throw new \InvalidArgumentException('non-nullable notification_code cannot be null');
        }
        if ((mb_strlen($notification_code) > 1)) {
            throw new \InvalidArgumentException('invalid length for $notification_code when calling ShipmentServiceOptionsNotification., must be smaller than or equal to 1.');
        }
        if ((mb_strlen($notification_code) < 1)) {
            throw new \InvalidArgumentException('invalid length for $notification_code when calling ShipmentServiceOptionsNotification., must be bigger than or equal to 1.');
        }

        $this->container['notification_code'] = $notification_code;

        return $this;
    }

    /**
     * Gets e_mail
     *
     * @return \AntibodiesOnline\UpsApi\Shipping\NotificationEMail
     */
    public function getEMail()
    {
        return $this->container['e_mail'];
    }

    /**
     * Sets e_mail
     *
     * @param \AntibodiesOnline\UpsApi\Shipping\NotificationEMail $e_mail e_mail
     *
     * @return self
     */
    public function setEMail($e_mail)
    {
        if (is_null($e_mail)) {
            throw new \InvalidArgumentException('non-nullable e_mail cannot be null');
        }
        $this->container['e_mail'] = $e_mail;

        return $this;
    }

    /**
     * Gets voice_message
     *
     * @return \AntibodiesOnline\UpsApi\Shipping\NotificationVoiceMessage|null
     */
    public function getVoiceMessage()
    {
        return $this->container['voice_message'];
    }

    /**
     * Sets voice_message
     *
     * @param \AntibodiesOnline\UpsApi\Shipping\NotificationVoiceMessage|null $voice_message voice_message
     *
     * @return self
     */
    public function setVoiceMessage($voice_message)
    {
        if (is_null($voice_message)) {
            throw new \InvalidArgumentException('non-nullable voice_message cannot be null');
        }
        $this->container['voice_message'] = $voice_message;

        return $this;
    }

    /**
     * Gets text_message
     *
     * @return \AntibodiesOnline\UpsApi\Shipping\NotificationTextMessage|null
     */
    public function getTextMessage()
    {
        return $this->container['text_message'];
    }

    /**
     * Sets text_message
     *
     * @param \AntibodiesOnline\UpsApi\Shipping\NotificationTextMessage|null $text_message text_message
     *
     * @return self
     */
    public function setTextMessage($text_message)
    {
        if (is_null($text_message)) {
            throw new \InvalidArgumentException('non-nullable text_message cannot be null');
        }
        $this->container['text_message'] = $text_message;

        return $this;
    }

    /**
     * Gets locale
     *
     * @return \AntibodiesOnline\UpsApi\Shipping\NotificationLocale|null
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }

    /**
     * Sets locale
     *
     * @param \AntibodiesOnline\UpsApi\Shipping\NotificationLocale|null $locale locale
     *
     * @return self
     */
    public function setLocale($locale)
    {
        if (is_null($locale)) {
            throw new \InvalidArgumentException('non-nullable locale cannot be null');
        }
        $this->container['locale'] = $locale;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


