<?php
/**
 * DefaultApi
 * PHP version 7.4
 *
 * @category Class
 * @package  AntibodiesOnline\UpsApi\Shipping
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ship
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AntibodiesOnline\UpsApi\Shipping\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use AntibodiesOnline\UpsApi\Shipping\ApiException;
use AntibodiesOnline\UpsApi\Shipping\Configuration;
use AntibodiesOnline\UpsApi\Shipping\HeaderSelector;
use AntibodiesOnline\UpsApi\Shipping\ObjectSerializer;

/**
 * DefaultApi Class Doc Comment
 *
 * @category Class
 * @package  AntibodiesOnline\UpsApi\Shipping
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'labelRecovery' => [
            'application/json',
        ],
        'shipment' => [
            'application/json',
        ],
        'voidShipment' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation labelRecovery
     *
     * Label Recovery
     *
     * @param  string $version When UPS introduces new elements in the  response that are not associated with new  request elements, Subversion is used. This  ensures backward compatibility.  v1  original features of the application. No  support for CODTurn-inPage, HighValueReport  or InternationalForms features returned in the  response v1701  includes support for CODTurn-inPage  features returned in the response. V1903  Length 5 (required)
     * @param  \AntibodiesOnline\UpsApi\Shipping\Model\LABELRECOVERYRequestWrapper $labelrecovery_request_wrapper Generate sample code for popular API requests by selecting an example below. To view a full sample request and response, first click \&quot;Authorize\&quot; and enter your application credentials, then populate the required parameters above and click \&quot;Try it out\&quot;. (required)
     * @param  string $trans_id An identifier unique to the request. Length 32 (optional)
     * @param  string $transaction_src An identifier of the client/source application that is making the request.Length 512 (optional, default to 'testing')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['labelRecovery'] to see the possible values for this operation
     *
     * @throws \AntibodiesOnline\UpsApi\Shipping\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \AntibodiesOnline\UpsApi\Shipping\Model\LABELRECOVERYResponseWrapper
     */
    public function labelRecovery($version, $labelrecovery_request_wrapper, $trans_id = null, $transaction_src = 'testing', string $contentType = self::contentTypes['labelRecovery'][0])
    {
        list($response) = $this->labelRecoveryWithHttpInfo($version, $labelrecovery_request_wrapper, $trans_id, $transaction_src, $contentType);
        return $response;
    }

    /**
     * Operation labelRecoveryWithHttpInfo
     *
     * Label Recovery
     *
     * @param  string $version When UPS introduces new elements in the  response that are not associated with new  request elements, Subversion is used. This  ensures backward compatibility.  v1  original features of the application. No  support for CODTurn-inPage, HighValueReport  or InternationalForms features returned in the  response v1701  includes support for CODTurn-inPage  features returned in the response. V1903  Length 5 (required)
     * @param  \AntibodiesOnline\UpsApi\Shipping\Model\LABELRECOVERYRequestWrapper $labelrecovery_request_wrapper Generate sample code for popular API requests by selecting an example below. To view a full sample request and response, first click \&quot;Authorize\&quot; and enter your application credentials, then populate the required parameters above and click \&quot;Try it out\&quot;. (required)
     * @param  string $trans_id An identifier unique to the request. Length 32 (optional)
     * @param  string $transaction_src An identifier of the client/source application that is making the request.Length 512 (optional, default to 'testing')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['labelRecovery'] to see the possible values for this operation
     *
     * @throws \AntibodiesOnline\UpsApi\Shipping\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \AntibodiesOnline\UpsApi\Shipping\Model\LABELRECOVERYResponseWrapper, HTTP status code, HTTP response headers (array of strings)
     */
    public function labelRecoveryWithHttpInfo($version, $labelrecovery_request_wrapper, $trans_id = null, $transaction_src = 'testing', string $contentType = self::contentTypes['labelRecovery'][0])
    {
        $request = $this->labelRecoveryRequest($version, $labelrecovery_request_wrapper, $trans_id, $transaction_src, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\AntibodiesOnline\UpsApi\Shipping\Model\LABELRECOVERYResponseWrapper' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\AntibodiesOnline\UpsApi\Shipping\Model\LABELRECOVERYResponseWrapper' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                 );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\AntibodiesOnline\UpsApi\Shipping\Model\LABELRECOVERYResponseWrapper', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\AntibodiesOnline\UpsApi\Shipping\Model\LABELRECOVERYResponseWrapper';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AntibodiesOnline\UpsApi\Shipping\Model\LABELRECOVERYResponseWrapper',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation labelRecoveryAsync
     *
     * Label Recovery
     *
     * @param  string $version When UPS introduces new elements in the  response that are not associated with new  request elements, Subversion is used. This  ensures backward compatibility.  v1  original features of the application. No  support for CODTurn-inPage, HighValueReport  or InternationalForms features returned in the  response v1701  includes support for CODTurn-inPage  features returned in the response. V1903  Length 5 (required)
     * @param  \AntibodiesOnline\UpsApi\Shipping\Model\LABELRECOVERYRequestWrapper $labelrecovery_request_wrapper Generate sample code for popular API requests by selecting an example below. To view a full sample request and response, first click \&quot;Authorize\&quot; and enter your application credentials, then populate the required parameters above and click \&quot;Try it out\&quot;. (required)
     * @param  string $trans_id An identifier unique to the request. Length 32 (optional)
     * @param  string $transaction_src An identifier of the client/source application that is making the request.Length 512 (optional, default to 'testing')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['labelRecovery'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function labelRecoveryAsync($version, $labelrecovery_request_wrapper, $trans_id = null, $transaction_src = 'testing', string $contentType = self::contentTypes['labelRecovery'][0])
    {
        return $this->labelRecoveryAsyncWithHttpInfo($version, $labelrecovery_request_wrapper, $trans_id, $transaction_src, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation labelRecoveryAsyncWithHttpInfo
     *
     * Label Recovery
     *
     * @param  string $version When UPS introduces new elements in the  response that are not associated with new  request elements, Subversion is used. This  ensures backward compatibility.  v1  original features of the application. No  support for CODTurn-inPage, HighValueReport  or InternationalForms features returned in the  response v1701  includes support for CODTurn-inPage  features returned in the response. V1903  Length 5 (required)
     * @param  \AntibodiesOnline\UpsApi\Shipping\Model\LABELRECOVERYRequestWrapper $labelrecovery_request_wrapper Generate sample code for popular API requests by selecting an example below. To view a full sample request and response, first click \&quot;Authorize\&quot; and enter your application credentials, then populate the required parameters above and click \&quot;Try it out\&quot;. (required)
     * @param  string $trans_id An identifier unique to the request. Length 32 (optional)
     * @param  string $transaction_src An identifier of the client/source application that is making the request.Length 512 (optional, default to 'testing')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['labelRecovery'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function labelRecoveryAsyncWithHttpInfo($version, $labelrecovery_request_wrapper, $trans_id = null, $transaction_src = 'testing', string $contentType = self::contentTypes['labelRecovery'][0])
    {
        $returnType = '\AntibodiesOnline\UpsApi\Shipping\Model\LABELRECOVERYResponseWrapper';
        $request = $this->labelRecoveryRequest($version, $labelrecovery_request_wrapper, $trans_id, $transaction_src, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'labelRecovery'
     *
     * @param  string $version When UPS introduces new elements in the  response that are not associated with new  request elements, Subversion is used. This  ensures backward compatibility.  v1  original features of the application. No  support for CODTurn-inPage, HighValueReport  or InternationalForms features returned in the  response v1701  includes support for CODTurn-inPage  features returned in the response. V1903  Length 5 (required)
     * @param  \AntibodiesOnline\UpsApi\Shipping\Model\LABELRECOVERYRequestWrapper $labelrecovery_request_wrapper Generate sample code for popular API requests by selecting an example below. To view a full sample request and response, first click \&quot;Authorize\&quot; and enter your application credentials, then populate the required parameters above and click \&quot;Try it out\&quot;. (required)
     * @param  string $trans_id An identifier unique to the request. Length 32 (optional)
     * @param  string $transaction_src An identifier of the client/source application that is making the request.Length 512 (optional, default to 'testing')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['labelRecovery'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function labelRecoveryRequest($version, $labelrecovery_request_wrapper, $trans_id = null, $transaction_src = 'testing', string $contentType = self::contentTypes['labelRecovery'][0])
    {

        // verify the required parameter 'version' is set
        if ($version === null || (is_array($version) && count($version) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $version when calling labelRecovery'
            );
        }
        
        // verify the required parameter 'labelrecovery_request_wrapper' is set
        if ($labelrecovery_request_wrapper === null || (is_array($labelrecovery_request_wrapper) && count($labelrecovery_request_wrapper) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $labelrecovery_request_wrapper when calling labelRecovery'
            );
        }




        $resourcePath = '/labels/{version}/recovery';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($trans_id !== null) {
            $headerParams['transId'] = ObjectSerializer::toHeaderValue($trans_id);
        }
        // header params
        if ($transaction_src !== null) {
            $headerParams['transactionSrc'] = ObjectSerializer::toHeaderValue($transaction_src);
        }

        // path params
        if ($version !== null) {
            $resourcePath = str_replace(
                '{' . 'version' . '}',
                ObjectSerializer::toPathValue($version),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($labelrecovery_request_wrapper)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($labelrecovery_request_wrapper));
            } else {
                $httpBody = $labelrecovery_request_wrapper;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation shipment
     *
     * Shipment
     *
     * @param  string $version Indicates Ship API to display the new release features in  Rate API response based on Ship release. See the New  section for the latest Ship release. Supported values: v1, v1601, v1607, v1701, v1707, v1801, v1807, v2108, v2205 . Length 5 (required)
     * @param  \AntibodiesOnline\UpsApi\Shipping\Model\SHIPRequestWrapper $ship_request_wrapper Generate sample code for popular API requests by selecting an example below. To view a full sample request and response, first click \&quot;Authorize\&quot; and enter your application credentials, then populate the required parameters above and click \&quot;Try it out\&quot;. (required)
     * @param  string $trans_id An identifier unique to the request. Length 32 (optional)
     * @param  string $transaction_src An identifier of the client/source application that is making the request.Length 512 (optional, default to 'testing')
     * @param  string $additionaladdressvalidation Valid Values:  city &#x3D; validation will include city.Length 15 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipment'] to see the possible values for this operation
     *
     * @throws \AntibodiesOnline\UpsApi\Shipping\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \AntibodiesOnline\UpsApi\Shipping\Model\SHIPResponseWrapper
     */
    public function shipment($version, $ship_request_wrapper, $trans_id = null, $transaction_src = 'testing', $additionaladdressvalidation = null, string $contentType = self::contentTypes['shipment'][0])
    {
        list($response) = $this->shipmentWithHttpInfo($version, $ship_request_wrapper, $trans_id, $transaction_src, $additionaladdressvalidation, $contentType);
        return $response;
    }

    /**
     * Operation shipmentWithHttpInfo
     *
     * Shipment
     *
     * @param  string $version Indicates Ship API to display the new release features in  Rate API response based on Ship release. See the New  section for the latest Ship release. Supported values: v1, v1601, v1607, v1701, v1707, v1801, v1807, v2108, v2205 . Length 5 (required)
     * @param  \AntibodiesOnline\UpsApi\Shipping\Model\SHIPRequestWrapper $ship_request_wrapper Generate sample code for popular API requests by selecting an example below. To view a full sample request and response, first click \&quot;Authorize\&quot; and enter your application credentials, then populate the required parameters above and click \&quot;Try it out\&quot;. (required)
     * @param  string $trans_id An identifier unique to the request. Length 32 (optional)
     * @param  string $transaction_src An identifier of the client/source application that is making the request.Length 512 (optional, default to 'testing')
     * @param  string $additionaladdressvalidation Valid Values:  city &#x3D; validation will include city.Length 15 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipment'] to see the possible values for this operation
     *
     * @throws \AntibodiesOnline\UpsApi\Shipping\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \AntibodiesOnline\UpsApi\Shipping\Model\SHIPResponseWrapper, HTTP status code, HTTP response headers (array of strings)
     */
    public function shipmentWithHttpInfo($version, $ship_request_wrapper, $trans_id = null, $transaction_src = 'testing', $additionaladdressvalidation = null, string $contentType = self::contentTypes['shipment'][0])
    {
        $request = $this->shipmentRequest($version, $ship_request_wrapper, $trans_id, $transaction_src, $additionaladdressvalidation, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\AntibodiesOnline\UpsApi\Shipping\Model\SHIPResponseWrapper' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\AntibodiesOnline\UpsApi\Shipping\Model\SHIPResponseWrapper' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                 );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\AntibodiesOnline\UpsApi\Shipping\Model\SHIPResponseWrapper', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\AntibodiesOnline\UpsApi\Shipping\Model\SHIPResponseWrapper';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AntibodiesOnline\UpsApi\Shipping\Model\SHIPResponseWrapper',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation shipmentAsync
     *
     * Shipment
     *
     * @param  string $version Indicates Ship API to display the new release features in  Rate API response based on Ship release. See the New  section for the latest Ship release. Supported values: v1, v1601, v1607, v1701, v1707, v1801, v1807, v2108, v2205 . Length 5 (required)
     * @param  \AntibodiesOnline\UpsApi\Shipping\Model\SHIPRequestWrapper $ship_request_wrapper Generate sample code for popular API requests by selecting an example below. To view a full sample request and response, first click \&quot;Authorize\&quot; and enter your application credentials, then populate the required parameters above and click \&quot;Try it out\&quot;. (required)
     * @param  string $trans_id An identifier unique to the request. Length 32 (optional)
     * @param  string $transaction_src An identifier of the client/source application that is making the request.Length 512 (optional, default to 'testing')
     * @param  string $additionaladdressvalidation Valid Values:  city &#x3D; validation will include city.Length 15 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shipmentAsync($version, $ship_request_wrapper, $trans_id = null, $transaction_src = 'testing', $additionaladdressvalidation = null, string $contentType = self::contentTypes['shipment'][0])
    {
        return $this->shipmentAsyncWithHttpInfo($version, $ship_request_wrapper, $trans_id, $transaction_src, $additionaladdressvalidation, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation shipmentAsyncWithHttpInfo
     *
     * Shipment
     *
     * @param  string $version Indicates Ship API to display the new release features in  Rate API response based on Ship release. See the New  section for the latest Ship release. Supported values: v1, v1601, v1607, v1701, v1707, v1801, v1807, v2108, v2205 . Length 5 (required)
     * @param  \AntibodiesOnline\UpsApi\Shipping\Model\SHIPRequestWrapper $ship_request_wrapper Generate sample code for popular API requests by selecting an example below. To view a full sample request and response, first click \&quot;Authorize\&quot; and enter your application credentials, then populate the required parameters above and click \&quot;Try it out\&quot;. (required)
     * @param  string $trans_id An identifier unique to the request. Length 32 (optional)
     * @param  string $transaction_src An identifier of the client/source application that is making the request.Length 512 (optional, default to 'testing')
     * @param  string $additionaladdressvalidation Valid Values:  city &#x3D; validation will include city.Length 15 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shipmentAsyncWithHttpInfo($version, $ship_request_wrapper, $trans_id = null, $transaction_src = 'testing', $additionaladdressvalidation = null, string $contentType = self::contentTypes['shipment'][0])
    {
        $returnType = '\AntibodiesOnline\UpsApi\Shipping\Model\SHIPResponseWrapper';
        $request = $this->shipmentRequest($version, $ship_request_wrapper, $trans_id, $transaction_src, $additionaladdressvalidation, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'shipment'
     *
     * @param  string $version Indicates Ship API to display the new release features in  Rate API response based on Ship release. See the New  section for the latest Ship release. Supported values: v1, v1601, v1607, v1701, v1707, v1801, v1807, v2108, v2205 . Length 5 (required)
     * @param  \AntibodiesOnline\UpsApi\Shipping\Model\SHIPRequestWrapper $ship_request_wrapper Generate sample code for popular API requests by selecting an example below. To view a full sample request and response, first click \&quot;Authorize\&quot; and enter your application credentials, then populate the required parameters above and click \&quot;Try it out\&quot;. (required)
     * @param  string $trans_id An identifier unique to the request. Length 32 (optional)
     * @param  string $transaction_src An identifier of the client/source application that is making the request.Length 512 (optional, default to 'testing')
     * @param  string $additionaladdressvalidation Valid Values:  city &#x3D; validation will include city.Length 15 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shipment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function shipmentRequest($version, $ship_request_wrapper, $trans_id = null, $transaction_src = 'testing', $additionaladdressvalidation = null, string $contentType = self::contentTypes['shipment'][0])
    {

        // verify the required parameter 'version' is set
        if ($version === null || (is_array($version) && count($version) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $version when calling shipment'
            );
        }
        
        // verify the required parameter 'ship_request_wrapper' is set
        if ($ship_request_wrapper === null || (is_array($ship_request_wrapper) && count($ship_request_wrapper) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ship_request_wrapper when calling shipment'
            );
        }



        

        $resourcePath = '/shipments/{version}/ship';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $additionaladdressvalidation,
            'additionaladdressvalidation', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($trans_id !== null) {
            $headerParams['transId'] = ObjectSerializer::toHeaderValue($trans_id);
        }
        // header params
        if ($transaction_src !== null) {
            $headerParams['transactionSrc'] = ObjectSerializer::toHeaderValue($transaction_src);
        }

        // path params
        if ($version !== null) {
            $resourcePath = str_replace(
                '{' . 'version' . '}',
                ObjectSerializer::toPathValue($version),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($ship_request_wrapper)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($ship_request_wrapper));
            } else {
                $httpBody = $ship_request_wrapper;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation voidShipment
     *
     * Void Shipment
     *
     * @param  string $version API Version (required)
     * @param  string $shipmentidentificationnumber The shipment&#39;s identification number  Alpha-numeric. Must pass 1Z rules. Must be  upper case. Length 18 (required)
     * @param  string $trans_id An identifier unique to the request. Length 32 (optional)
     * @param  string $transaction_src An identifier of the client/source application that is making the request.Length 512 (optional, default to 'testing')
     * @param  string $trackingnumber The package&#39;s tracking number. You may have  up to 20 different tracking numbers listed. If more than one tracking number, pass this  value as: trackingnumber&#x3D;  [\&quot;1ZISUS010330563105\&quot;,\&quot;1ZISUS01033056310 8\&quot;] with a coma separating each number. Alpha-numeric. Must pass 1Z rules. Must be  upper case. Length 18 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['voidShipment'] to see the possible values for this operation
     *
     * @throws \AntibodiesOnline\UpsApi\Shipping\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \AntibodiesOnline\UpsApi\Shipping\Model\VOIDSHIPMENTResponseWrapper
     */
    public function voidShipment($version, $shipmentidentificationnumber, $trans_id = null, $transaction_src = 'testing', $trackingnumber = null, string $contentType = self::contentTypes['voidShipment'][0])
    {
        list($response) = $this->voidShipmentWithHttpInfo($version, $shipmentidentificationnumber, $trans_id, $transaction_src, $trackingnumber, $contentType);
        return $response;
    }

    /**
     * Operation voidShipmentWithHttpInfo
     *
     * Void Shipment
     *
     * @param  string $version API Version (required)
     * @param  string $shipmentidentificationnumber The shipment&#39;s identification number  Alpha-numeric. Must pass 1Z rules. Must be  upper case. Length 18 (required)
     * @param  string $trans_id An identifier unique to the request. Length 32 (optional)
     * @param  string $transaction_src An identifier of the client/source application that is making the request.Length 512 (optional, default to 'testing')
     * @param  string $trackingnumber The package&#39;s tracking number. You may have  up to 20 different tracking numbers listed. If more than one tracking number, pass this  value as: trackingnumber&#x3D;  [\&quot;1ZISUS010330563105\&quot;,\&quot;1ZISUS01033056310 8\&quot;] with a coma separating each number. Alpha-numeric. Must pass 1Z rules. Must be  upper case. Length 18 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['voidShipment'] to see the possible values for this operation
     *
     * @throws \AntibodiesOnline\UpsApi\Shipping\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \AntibodiesOnline\UpsApi\Shipping\Model\VOIDSHIPMENTResponseWrapper, HTTP status code, HTTP response headers (array of strings)
     */
    public function voidShipmentWithHttpInfo($version, $shipmentidentificationnumber, $trans_id = null, $transaction_src = 'testing', $trackingnumber = null, string $contentType = self::contentTypes['voidShipment'][0])
    {
        $request = $this->voidShipmentRequest($version, $shipmentidentificationnumber, $trans_id, $transaction_src, $trackingnumber, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\AntibodiesOnline\UpsApi\Shipping\Model\VOIDSHIPMENTResponseWrapper' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\AntibodiesOnline\UpsApi\Shipping\Model\VOIDSHIPMENTResponseWrapper' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                 );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\AntibodiesOnline\UpsApi\Shipping\Model\VOIDSHIPMENTResponseWrapper', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\AntibodiesOnline\UpsApi\Shipping\Model\VOIDSHIPMENTResponseWrapper';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AntibodiesOnline\UpsApi\Shipping\Model\VOIDSHIPMENTResponseWrapper',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation voidShipmentAsync
     *
     * Void Shipment
     *
     * @param  string $version API Version (required)
     * @param  string $shipmentidentificationnumber The shipment&#39;s identification number  Alpha-numeric. Must pass 1Z rules. Must be  upper case. Length 18 (required)
     * @param  string $trans_id An identifier unique to the request. Length 32 (optional)
     * @param  string $transaction_src An identifier of the client/source application that is making the request.Length 512 (optional, default to 'testing')
     * @param  string $trackingnumber The package&#39;s tracking number. You may have  up to 20 different tracking numbers listed. If more than one tracking number, pass this  value as: trackingnumber&#x3D;  [\&quot;1ZISUS010330563105\&quot;,\&quot;1ZISUS01033056310 8\&quot;] with a coma separating each number. Alpha-numeric. Must pass 1Z rules. Must be  upper case. Length 18 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['voidShipment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function voidShipmentAsync($version, $shipmentidentificationnumber, $trans_id = null, $transaction_src = 'testing', $trackingnumber = null, string $contentType = self::contentTypes['voidShipment'][0])
    {
        return $this->voidShipmentAsyncWithHttpInfo($version, $shipmentidentificationnumber, $trans_id, $transaction_src, $trackingnumber, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation voidShipmentAsyncWithHttpInfo
     *
     * Void Shipment
     *
     * @param  string $version API Version (required)
     * @param  string $shipmentidentificationnumber The shipment&#39;s identification number  Alpha-numeric. Must pass 1Z rules. Must be  upper case. Length 18 (required)
     * @param  string $trans_id An identifier unique to the request. Length 32 (optional)
     * @param  string $transaction_src An identifier of the client/source application that is making the request.Length 512 (optional, default to 'testing')
     * @param  string $trackingnumber The package&#39;s tracking number. You may have  up to 20 different tracking numbers listed. If more than one tracking number, pass this  value as: trackingnumber&#x3D;  [\&quot;1ZISUS010330563105\&quot;,\&quot;1ZISUS01033056310 8\&quot;] with a coma separating each number. Alpha-numeric. Must pass 1Z rules. Must be  upper case. Length 18 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['voidShipment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function voidShipmentAsyncWithHttpInfo($version, $shipmentidentificationnumber, $trans_id = null, $transaction_src = 'testing', $trackingnumber = null, string $contentType = self::contentTypes['voidShipment'][0])
    {
        $returnType = '\AntibodiesOnline\UpsApi\Shipping\Model\VOIDSHIPMENTResponseWrapper';
        $request = $this->voidShipmentRequest($version, $shipmentidentificationnumber, $trans_id, $transaction_src, $trackingnumber, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'voidShipment'
     *
     * @param  string $version API Version (required)
     * @param  string $shipmentidentificationnumber The shipment&#39;s identification number  Alpha-numeric. Must pass 1Z rules. Must be  upper case. Length 18 (required)
     * @param  string $trans_id An identifier unique to the request. Length 32 (optional)
     * @param  string $transaction_src An identifier of the client/source application that is making the request.Length 512 (optional, default to 'testing')
     * @param  string $trackingnumber The package&#39;s tracking number. You may have  up to 20 different tracking numbers listed. If more than one tracking number, pass this  value as: trackingnumber&#x3D;  [\&quot;1ZISUS010330563105\&quot;,\&quot;1ZISUS01033056310 8\&quot;] with a coma separating each number. Alpha-numeric. Must pass 1Z rules. Must be  upper case. Length 18 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['voidShipment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function voidShipmentRequest($version, $shipmentidentificationnumber, $trans_id = null, $transaction_src = 'testing', $trackingnumber = null, string $contentType = self::contentTypes['voidShipment'][0])
    {

        // verify the required parameter 'version' is set
        if ($version === null || (is_array($version) && count($version) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $version when calling voidShipment'
            );
        }

        // verify the required parameter 'shipmentidentificationnumber' is set
        if ($shipmentidentificationnumber === null || (is_array($shipmentidentificationnumber) && count($shipmentidentificationnumber) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shipmentidentificationnumber when calling voidShipment'
            );
        }
        


        

        $resourcePath = '/shipments/{version}/void/cancel/{shipmentidentificationnumber}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $trackingnumber,
            'trackingnumber', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($trans_id !== null) {
            $headerParams['transId'] = ObjectSerializer::toHeaderValue($trans_id);
        }
        // header params
        if ($transaction_src !== null) {
            $headerParams['transactionSrc'] = ObjectSerializer::toHeaderValue($transaction_src);
        }

        // path params
        if ($version !== null) {
            $resourcePath = str_replace(
                '{' . 'version' . '}',
                ObjectSerializer::toPathValue($version),
                $resourcePath
            );
        }
        // path params
        if ($shipmentidentificationnumber !== null) {
            $resourcePath = str_replace(
                '{' . 'shipmentidentificationnumber' . '}',
                ObjectSerializer::toPathValue($shipmentidentificationnumber),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
