<?php
/**
 * PackageServiceOptionsHazMatTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AntibodiesOnline\UpsApi\Rating
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Rate
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AntibodiesOnline\UpsApi\Rating\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PackageServiceOptionsHazMatTest Class Doc Comment
 *
 * @category    Class
 * @description Container to hold HazMat information.  Applies only if SubVersion is greater than or equal to 1701.
 * @package     AntibodiesOnline\UpsApi\Rating
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PackageServiceOptionsHazMatTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PackageServiceOptionsHazMat"
     */
    public function testPackageServiceOptionsHazMat()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "package_identifier"
     */
    public function testPropertyPackageIdentifier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "q_value"
     */
    public function testPropertyQValue()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "over_packed_indicator"
     */
    public function testPropertyOverPackedIndicator()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "all_packed_in_one_indicator"
     */
    public function testPropertyAllPackedInOneIndicator()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "haz_mat_chemical_record"
     */
    public function testPropertyHazMatChemicalRecord()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
