<?php
/**
 * ProductExcludeFromFormTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AntibodiesOnline\UpsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ship
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AntibodiesOnline\UpsApi\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ProductExcludeFromFormTest Class Doc Comment
 *
 * @category    Class
 * @description Container tag for determining whether or not to exclude product information from a particular form.  If this container is not present we assume that the DEFAULT is selected which is \&quot;none\&quot; and all products will appear on all forms.
 * @package     AntibodiesOnline\UpsApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProductExcludeFromFormTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ProductExcludeFromForm"
     */
    public function testProductExcludeFromForm()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "form_type"
     */
    public function testPropertyFormType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
