<?php
/**
 * RatedShipmentTimeInTransitTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AntibodiesOnline\UpsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Rate
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AntibodiesOnline\UpsApi\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * RatedShipmentTimeInTransitTest Class Doc Comment
 *
 * @category    Class
 * @description Container for returned Time in Transit information.  Will only be returned if request option was either \&quot;ratetimeintransit\&quot; or \&quot;shoptimeintransit\&quot; and DeliveryTimeInformation container was present in request.
 * @package     AntibodiesOnline\UpsApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RatedShipmentTimeInTransitTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RatedShipmentTimeInTransit"
     */
    public function testRatedShipmentTimeInTransit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pickup_date"
     */
    public function testPropertyPickupDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "documents_only_indicator"
     */
    public function testPropertyDocumentsOnlyIndicator()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "package_bill_type"
     */
    public function testPropertyPackageBillType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "service_summary"
     */
    public function testPropertyServiceSummary()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "auto_duty_code"
     */
    public function testPropertyAutoDutyCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "disclaimer"
     */
    public function testPropertyDisclaimer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
