<?php
/**
 * ShipmentServiceOptionsRestrictedArticlesTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AntibodiesOnline\UpsApi\Rating
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Rate
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AntibodiesOnline\UpsApi\Rating\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ShipmentServiceOptionsRestrictedArticlesTest Class Doc Comment
 *
 * @category    Class
 * @description Restricted Articles container.  Valid for UPS World Wide Express Freight shipments.
 * @package     AntibodiesOnline\UpsApi\Rating
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ShipmentServiceOptionsRestrictedArticlesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ShipmentServiceOptionsRestrictedArticles"
     */
    public function testShipmentServiceOptionsRestrictedArticles()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "alcoholic_beverages_indicator"
     */
    public function testPropertyAlcoholicBeveragesIndicator()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "diagnostic_specimens_indicator"
     */
    public function testPropertyDiagnosticSpecimensIndicator()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "perishables_indicator"
     */
    public function testPropertyPerishablesIndicator()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "plants_indicator"
     */
    public function testPropertyPlantsIndicator()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "seeds_indicator"
     */
    public function testPropertySeedsIndicator()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "special_exceptions_indicator"
     */
    public function testPropertySpecialExceptionsIndicator()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tobacco_indicator"
     */
    public function testPropertyTobaccoIndicator()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "e_cigarettes_indicator"
     */
    public function testPropertyECigarettesIndicator()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hemp_cbd_indicator"
     */
    public function testPropertyHempCbdIndicator()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
